### ISSUE TITLE
CRAN failure

### ISSUE THREAD

**Issue by hadley** [jonocarroll/charcuterie#1]
Unfortunately the recent waldo release broke your package on CRAN because it no longer imports tibble, and your package was implicitly depending on it. The easiest fix is to just make the dependency explicit, by adding tibble to Suggests.

Many apologies for the hassle. Unfortunately we didn't discover this prior to CRAN release because we had a bug in the code that runs our revdep checks 🙁.

**Comment by jonocarroll** [comment]
I added `vctrs` as an explicit `Suggests` dependency; I was using `testthat::expect_vector()` which relies on `vctrs` which was previously available via `waldo` via `testthat`. 

Now on CRAN https://cran.r-project.org/package=charcuterie
